#服务注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

server:
  port: 8082

#spring设置
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jinfan1115/spring-cloud-microservices.git
          searchPaths: cloud-fyang-config-repo
